title: Lustauffotos.com
description: " "
author: tobi
# baseurl:            "/startbootstrap-clean-blog-jekyll"
url: http://www.lustauffotos.com/

remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll

# Social Profiles
# twitter_username:   rngtng
# github_username:    rngtng

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           25
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
