title: Lustauffotos
description: " "
author: tobi
url: http://www.lustauffotos.de/

remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll

# Social Profiles
twitter_username:   tobitobes

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-1074303-6

# Build settings
markdown:           kramdown
paginate:           25
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-admin

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      background: '/assets/header.png'
  -
    scope:
      path: ""
      type: "pages"
    values:
      background: '/assets/header.png'
